[package]
name = "bevy_editor_pls_core"
version = "0.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/jakobhellermann/bevy-inspector-egui/"
description = "In-App editor tools for bevy apps"

[features]
viewport = []

[dependencies]
bevy = { version = "0.8", default-features = false }
bevy-inspector-egui = "0.12"
indexmap = "1.7"
