[package]
name = "bevy_editor_pls_core"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
viewport = []

[dependencies]
bevy = { version = "0.7", default-features = false }
bevy-inspector-egui = "0.10"
indexmap = "1.7"
