[package]
name = "bevy_editor_pls"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
default_windows = ["bevy_editor_pls_default_windows", "bevy/bevy_render", "bevy/bevy_pbr"]
default = ["default_windows"]
viewport = ["bevy_editor_pls_default_windows/viewport"]

[dependencies]
bevy = { version = "0.8", default-features = false }
egui = "0.18.1"
bevy_editor_pls_core = { path = "../bevy_editor_pls_core" }
bevy_editor_pls_default_windows = { path = "../bevy_editor_pls_default_windows", optional = true }

[dev-dependencies]
bevy = { version = "0.8", default-features = false, features = [
    "bevy_winit",
    "x11",
] }

[[example]]
name = "load_gltf"
required-features = [ "bevy/png" ]
