[package]
name = "bevy_editor_pls_default_windows"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
viewport = []

[dependencies]
bevy = { version = "0.7", default-features = false }
bevy_editor_pls_core = { path = "../bevy_editor_pls_core" }
bevy-inspector-egui = "0.10"
bevy_mod_raycast = { git = "https://github.com/obsgolem/bevy_mod_raycast", branch = "release" }
indexmap = "1.7"
pretty-type-name = "1.0"
bevy_mod_debugdump = "0.4"
opener = "0.5.0"
