[package]
name = "bevy_editor_pls_default_windows"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
viewport = []

[dependencies]
bevy = { version = "0.6" }
bevy_editor_pls_core = { path = "../bevy_editor_pls_core" }
bevy-inspector-egui = "0.8"
bevy_mod_raycast = "0.3"
indexmap = "1.7"
pretty-type-name = "1.0"
